services:
  postgres_odds:
    image: postgres:17.6-alpine3.22
    container_name: postgres_odds
    environment:
      POSTGRES_USER: ${POSTGRES_USER_ODDS:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ODDS:-postgres}
      POSTGRES_DB: ${POSTGRES_DB_ODDS:-odds}
    ports:
      - "${POSTGRES_ODDS_PORT:-5432}:5432"
    restart: always
    volumes: 
      - './scripts/wait-for-postgres.sh:/wait-for-postgres.sh'

  postgres_bets:
    image: postgres:17.6-alpine3.22
    container_name: postgres_bets
    environment:
      POSTGRES_USER: ${POSTGRES_USER_BETS:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BETS:-postgres}
      POSTGRES_DB: ${POSTGRES_DB_BETS:-bets}
    ports:
      - "${POSTGRES_BETS_PORT:-5433}:5432"
    restart: always
    volumes: 
      - './scripts/wait-for-postgres.sh:/wait-for-postgres.sh'

  redis_bullmq:
    image: redis:7-alpine
    container_name: redis_bullmq
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    