// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: common.proto

/* eslint-disable */

export const BetTeam = { HOME: "HOME", AWAY: "AWAY" } as const;

export type BetTeam = typeof BetTeam[keyof typeof BetTeam];

export namespace BetTeam {
  export type HOME = typeof BetTeam.HOME;
  export type AWAY = typeof BetTeam.AWAY;
}

export interface PaginationDto {
  page: number;
  pageSize: number;
}

export interface PaginationMetadata {
  currentPage: number;
  totalPages: number;
  pageSize: number;
  totalItems: number;
}

export interface SuccessResponse {
  message: string;
}

export interface ErrorResponse {
  message: string;
  code: number;
}

export interface Empty {
}
